# -*- coding: utf-8 -*-
"""RFP summarization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nDgu1u_UHIaGxML06jSy1neBrjl9aIzk
"""

!pip install PyMuPDF
!pip install transformers

"""Run this code only id file is small...maximum 10 pages...else it takes too long to summarize.

"""

# Step 1: Install required libraries
!pip install PyMuPDF
!pip install transformers

# Step 2: Upload PDF
from google.colab import files
uploaded = files.upload()

# Step 3: Extract text from PDF
import fitz  # PyMuPDF

pdf_file_name = list(uploaded.keys())[0]
doc = fitz.open(pdf_file_name)

text = ""
for page in doc:
    text += page.get_text()

doc.close()

# Show the first 500 characters of the extracted text
print(text[:500])

# Step 4: Summarize the text
from transformers import pipeline

# Initialize the summarizer
summarizer = pipeline("summarization")

# Function to split text into chunks
def split_text(text, max_length):
    sentences = text.split('. ')
    chunks = []
    current_chunk = ""

    for sentence in sentences:
        if len(current_chunk) + len(sentence) + 1 <= max_length:
            current_chunk += sentence + ". "
        else:
            chunks.append(current_chunk.strip())
            current_chunk = sentence + ". "
    if current_chunk:
        chunks.append(current_chunk.strip())

    return chunks

# Split text into chunks (adjust the max_length as needed)
chunks = split_text(text, 1000)  # Using 1000 characters per chunk

# Summarize each chunk
summaries = []
for chunk in chunks:
    summary = summarizer(chunk, max_length=150, min_length=50, do_sample=False)
    summaries.append(summary[0]['summary_text'])

# Combine summaries
final_summary = " ".join(summaries)

# Display the final summary
print(final_summary)

"""run this when pdf is longer than 10 pages. mention number of pages to summarise in this portion of code......
def extract_text_from_pdf(pdf_path, max_pages=10):
"""

# Install dependencies (run once)
!pip install transformers pymupdf

# Imports
import fitz  # PyMuPDF
from transformers import pipeline
from google.colab import files

# File upload widget
uploaded = files.upload()

# Get uploaded filename
pdf_file = list(uploaded.keys())[0]

def extract_text_from_pdf(pdf_path, max_pages=10):
    """Extracts text from the first `max_pages` of a PDF file."""
    doc = fitz.open(pdf_path)
    text = "\n".join([doc[i].get_text() for i in range(min(max_pages, len(doc)))])
    doc.close()
    return text

def split_text(text, max_length=1000):
    """Splits text into chunks while maintaining sentence structure."""
    sentences = text.split('. ')
    chunks, current_chunk = [], ""

    for sentence in sentences:
        if len(current_chunk) + len(sentence) + 1 <= max_length:
            current_chunk += sentence + ". "
        else:
            chunks.append(current_chunk.strip())
            current_chunk = sentence + ". "

    if current_chunk:
        chunks.append(current_chunk.strip())

    return chunks

def summarize_chunks(chunks, summarizer):
    """Summarizes all chunks sequentially."""
    summaries = []
    for chunk in chunks:
        summary = summarizer(chunk, max_length=150, min_length=50, do_sample=False)[0]['summary_text']
        summaries.append(summary)
    return " ".join(summaries)

# Main Execution
text = extract_text_from_pdf(pdf_file, max_pages=10)
chunks = split_text(text)
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")
summary = summarize_chunks(chunks, summarizer)

# Output
print("🔍 Final Summary:\n")
print(summary)

